import { DM_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${dmSans.variable} antialiased`}>
        <div className="min-h-screen bg-[#e9eaec] p-4 sm:p-6 lg:p-8">
          <div className="mx-auto flex w-full max-w-[1120px] flex-col gap-1">
            <Navbar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
